CsomRest/Ivoryit.Tarefas/Ivoryit.Tarefas/Controllers/TarefaController.cs
using Ivoryit.Tarefas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Ivoryit.Tarefas.Controllers
{
    [Authorize]
    public class TarefaController : Controller
    {
        public ActionResult Index()
        {
            // CSOM
            var tarefaCsom = new TarefaCSOM();
            var tarefas = tarefaCsom.Listar();
            return View(tarefas);

            // REST
            //var tarefaRest = new TarefaREST();
            //var tarefas = tarefaRest.Listar();
            //return View(tarefas);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(TarefaModel tarefa)
        {
            // CSOM
            var tarefaCsom = new TarefaCSOM();
            tarefaCsom.Cadastrar(tarefa);
            return RedirectToAction("Index");

            // REST
            //var tarefaRest = new TarefaREST();
            //tarefaRest.Cadastrar(tarefa);
            //return RedirectToAction("Index");
        }

        public ActionResult Finalizar(int id)
        {
            // CSOM
            var tarefaCsom = new TarefaCSOM();
            tarefaCsom.Finalizar(id);
            return RedirectToAction("Index");

            // REST
            //var tarefaRest = new TarefaREST();
            //tarefaRest.Finalizar(id);
            //return RedirectToAction("Index");
        }

        public ActionResult Excluir(int id)
        {
            // CSOM
            var tarefaCsom = new TarefaCSOM();
            tarefaCsom.Excluir(id);
            return RedirectToAction("Index");

            // REST
            //var tarefaRest = new TarefaREST();
            //tarefaRest.Excluir(id);
            //return RedirectToAction("Index");
        }

        public ActionResult RelatorioTarefasAbertas()
        {
            // CSOM
            var tarefaCsom = new TarefaCSOM();
            var tarefas = tarefaCsom.ObterTarefasAbertas();
            return View(tarefas);

            // REST
            //var tarefaRest = new TarefaREST();
            //var tarefas = tarefaRest.ObterTarefasAbertas();
            //return View(tarefas);
        }

        public ActionResult Forum()
        {
            // CSOM
            var tarefaForumCsom = new TarefaForumCSOM();
            ViewBag.Mensagens = tarefaForumCsom.Listar();

            return View();
        }

        [HttpPost]
        public ActionResult Forum(TarefaForumModel tarefaForum)
        {
            // CSOM
            var tarefaForumCsom = new TarefaForumCSOM();
            tarefaForumCsom.Cadastrar(tarefaForum);
            return RedirectToAction("Forum");
        }
    }
}

CsomRest/Ivoryit.Tarefas/Ivoryit.Tarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gerenciador de Tarefas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Tarefas", "Index", "Tarefa")</li>
                    <li>@Html.ActionLink("Relatório de tarefas abertas", "RelatorioTarefasAbertas", "Tarefa")</li>
                    <li>@Html.ActionLink("Fórum", "Forum", "Tarefa")</li>
                </ul>

                @using (Html.BeginForm(
                    "Index", "Busca", 
                    FormMethod.Get, 
                    new {@class = "navbar-form navbar-right"})
                )
                {
                    <div class="form-group">
                        <input type="search" name="pesquisa" placeholder="Pesquisa" class="form-control">
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>